"""add pipeline to encode_job

Revision ID: 2964e7553e0e
Revises: 5e4cdf60f904
Create Date: 2026-07-30 10:38:39.947930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2964e7553e0e'
down_revision = '5e4cdf60f904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encode_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pipeline', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encode_jobs', schema=None) as batch_op:
        batch_op.drop_column('pipeline')

    # ### end Alembic commands ###
