"""Added ExperimentRun and is_synthetic flags

Revision ID: 5e4cdf60f904
Revises: 3ab58f9b8f10
Create Date: 2026-07-21 12:29:24.552977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e4cdf60f904'
down_revision = '3ab58f9b8f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('image_name', sa.String(length=255), nullable=False),
    sa.Column('image_size_kb', sa.Float(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('message_length', sa.Integer(), nullable=False),
    sa.Column('compression_ratio', sa.Float(), nullable=True),
    sa.Column('encode_time_ms', sa.Float(), nullable=True),
    sa.Column('decode_time_ms', sa.Float(), nullable=True),
    sa.Column('psnr', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_synthetic', sa.Boolean(), nullable=True))

    with op.batch_alter_table('encode_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_synthetic', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_synthetic', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_synthetic')

    with op.batch_alter_table('encode_jobs', schema=None) as batch_op:
        batch_op.drop_column('is_synthetic')

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_column('is_synthetic')

    op.drop_table('experiment_runs')
    # ### end Alembic commands ###
