"""remove analytics layer

Revision ID: 87e9cfa3e1cb
Revises: 2964e7553e0e
Create Date: 2026-08-03 13:37:57.854070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e9cfa3e1cb'
down_revision = '2964e7553e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experiment_runs')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_column('is_synthetic')

    with op.batch_alter_table('encode_jobs', schema=None) as batch_op:
        batch_op.drop_column('is_synthetic')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_synthetic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_synthetic', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('encode_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_synthetic', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_synthetic', sa.BOOLEAN(), nullable=True))

    op.create_table('experiment_runs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('image_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('image_size_kb', sa.FLOAT(), nullable=False),
    sa.Column('width', sa.INTEGER(), nullable=False),
    sa.Column('height', sa.INTEGER(), nullable=False),
    sa.Column('algorithm', sa.VARCHAR(length=100), nullable=False),
    sa.Column('message_length', sa.INTEGER(), nullable=False),
    sa.Column('compression_ratio', sa.FLOAT(), nullable=True),
    sa.Column('encode_time_ms', sa.FLOAT(), nullable=True),
    sa.Column('decode_time_ms', sa.FLOAT(), nullable=True),
    sa.Column('psnr', sa.FLOAT(), nullable=True),
    sa.Column('success', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
